Supported pull-base command and init-bare-push command in Linux shared folder with Windows.

diff --git a/bin/locommit b/bin/locommit
--- a/bin/locommit
+++ b/bin/locommit
@@ -75,8 +75,8 @@ function  LocalCommit() {
     local  rsyncUsed="${False}"
     if IsWindowsFolder  "${workingFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${workingFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${workingFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${workingFolderPath}"  "${LOCOMMIT_TMP}"
             workingFolderPath="${LOCOMMIT_TMP}${workingFolderPath}"
             pushd  "${workingFolderPath}" > /dev/null  ||  Error
             rsyncUsed="${True}"
@@ -226,8 +226,8 @@ function  Clone() {
     local  rsyncRepositoryUsed="${False}"
     if IsWindowsFolder  "${repositoryFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${repositoryFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${repositoryFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${repositoryFolderPath}"  "${LOCOMMIT_TMP}"
             repositoryFolderPath="${LOCOMMIT_TMP}${repositoryFolderPath}"
             rsyncRepositoryUsed="${True}"
         else
@@ -237,8 +237,8 @@ function  Clone() {
     local  rsyncDestinationUsed="${False}"
     if IsWindowsFolder  "${destinationFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${destinationFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${destinationFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${destinationFolderPath}"  "${LOCOMMIT_TMP}"
             destinationFolderPath="${LOCOMMIT_TMP}${destinationFolderPath}"
             rsyncDestinationUsed="${True}"
         else
@@ -456,8 +456,8 @@ function  PushFolder() {
     local  rsyncUsed="${False}"
     if IsWindowsFolder  "${workingFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${workingFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${workingFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${workingFolderPath}"  "${LOCOMMIT_TMP}"
             workingFolderPath="${LOCOMMIT_TMP}${workingFolderPath}"
             pushd  "${workingFolderPath}" > /dev/null  ||  Error
             local  rsyncUsed="${True}"
@@ -514,7 +514,7 @@ function  PushWithoutLocalCommit() {
 
 function  Pull() {
     #   *   4 (pulled)
-    #   |\
+    #   |\    <-- Pull command
     #   | * 3 _repository
     #   * | 2 .commit_new
     #   |/
@@ -555,8 +555,8 @@ function  PullSub() {
     local  rsyncWorkingUsed="${False}"
     if IsWindowsFolder  "${workingFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${workingFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${workingFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${workingFolderPath}"  "${LOCOMMIT_TMP}"
             workingFolderPath="${LOCOMMIT_TMP}${workingFolderPath}"
             pushd  "${workingFolderPath}" > /dev/null  ||  Error
             local  rsyncWorkingUsed="${True}"
@@ -566,8 +566,8 @@ function  PullSub() {
     fi
     if IsWindowsFolder  "${repositoryFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${repositoryFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${repositoryFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${repositoryFolderPath}"  "${LOCOMMIT_TMP}"
             repositoryFolderPath="${LOCOMMIT_TMP}${repositoryFolderPath}"
         else
             echo  "LOCOMMIT_TMP environment variable is not set though \"${repositoryFolderPath}\" is Windows shared folder."
@@ -614,20 +614,20 @@ function  PullSub() {
                 mv  "${repositoryFolderPath}/.commit"  ".commit_theirs"
             fi
         fi
-        echo  "Copied a repository folder to \".commit_theirs\" folder"
+        echo  'Copied a repository folder to ".commit_theirs" folder'
 
     #// Create ".commit_ours" folder
     if [ "${source}" == ".commit_new" ]; then
         DeleteFolder  ".commit_ours"
         mv  ".commit_new"  ".commit_ours"
-        echo  "Renamed \".commit_new\" folder to \".commit_ours\" folder"
+        echo  'Renamed ".commit_new" folder to ".commit_ours" folder'
     else
         DeleteFolder    ".commit_ours"
         mkdir -p  ".commit_ours"
         ls -a ".commit" | grep -v  -e "^\.$"  -e "^\.\.$" | xargs  -I {} \
             cp -Rap  ".commit/{}"  ".commit_ours"
         DeleteFolder  ".commit_ours/.git"
-        echo  "Copied \".commit\" folder to \".commit_ours\" folder"
+        echo  'Copied ".commit" folder to ".commit_ours" folder'
     fi
 
     #// Add to stage in parent .git, if the parent .git includes current folder.
@@ -638,7 +638,7 @@ function  PullSub() {
     fi
 
     #// Make a ".git" folder that has "commit_reposiroty" branch
-    echo  "Pull from \".commit_theirs\" folder"
+    echo  'Pull from ".commit_theirs" folder'
     local  currentBranch=$( git rev-parse --abbrev-ref HEAD  || echo "(ERROR)" )
     ErrorIfLastIs  "${currentBranch}"  "(ERROR)"
 
@@ -656,7 +656,7 @@ function  PullSub() {
                 if [ "${option}" == "--pull" ]; then
                     echo  "Added a commit of \".commit\" contents."
                 else
-                    echo  "Added a commit of old \"${baseFolderRelativePath}\" contents."
+                    echo  "Added a commit of old \"${baseFolderRelativePath}\" contents (pull base version)."
                 fi
                 if [ "$(git status --short)" != "" ]; then
                     mv  ".git"  ".."
@@ -743,15 +743,15 @@ function  PullSub() {
         #// Diff
         local  diff_output="$( diff -qr  ".commit"  ".commit_theirs" )"
         if [ "${option}" == "--pull-base" ]; then
-            echo  "Renamed \".commit\" folder to \".commit_old_base\" folder"
-            echo  "Renamed \".commit_theirs\" folder to new \"${baseFolderPath}\" folder"
+            echo  'Renamed ".commit" folder to ".commit_old_base" folder (pull base version)'
+            echo  'Renamed ".commit_theirs" folder to new '"\"${baseFolderPath}\" folder (pull base version)"
             diff_output="$( echo "${diff_output}"  |
                 sed -E 's|.commit/|.commit_old_base/|g'  |
                 sed -E 's|.commit_theirs/|new _base/|g'  )"
         fi
         ErrorIfLastIs  "${diff_output}"  "(ERROR)"
         if [ "${option}" == "--pull" ]; then
-            echo  "Updated files by this merge from \".commit_theirs\" folder:"
+            echo  'Updated files by this merge from ".commit_theirs" folder (pull base version):'
         else
             echo  "Updated files by this merge from new \"${baseFolderPath}\" folder:"
         fi
@@ -782,7 +782,7 @@ function  PullSub() {
 
 function  PullBase() {
     #   *   5 (pulled)
-    #   |\
+    #   |\    <-- PullBase command
     #   | * 4 _repository
     #   * | 3 .commit_new
     #   * | 2 .commit
@@ -809,29 +809,37 @@ function  PullBase() {
     AssertExist  "${baseFolderPath}"
     AssertExist  "${repositoryFolderPath}"
 
-    echo  "Renamed \".commit\" folder to \".commit_this\" folder"
-    echo  "Renamed \"${baseFolderPath}\" folder to \".commit\" folder"
-    mv  ".commit"  ".commit_this"
-    mv  "${baseFolderPath}"  ".commit"
+    echo  'Renamed ".commit" folder to ".commit_this" folder'
+    echo  "Renamed \"${baseFolderPath}\""' folder to ".commit" folder'
+    StartInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
+    mv  ".commit"  ".commit_this"  ||  Error
+    mv  "${baseFolderPath}"  ".commit"  ||  Error
+    EndInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"s
 
     #// Pull command
+    echo  "Start pull command (of pull base version)"
     shift
-    PullSub  "$1"  --pull-base  "${baseFolderPath}"
 
+    PullSub  "$1"  --pull-base  "${baseFolderPath}"
+    echo  "End pull command (of pull base version)"
+
+    #// After pull command
+    StartInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
     if [ -e ".commit_theirs" ]; then
         #// There is echo command in PullSub
-        mv  ".commit"  ".commit_old_base"
-        mv  ".commit_theirs"  "${baseFolderPath}"
+        mv  ".commit"  ".commit_old_base"  ||  Error
+        mv  ".commit_theirs"  "${baseFolderPath}"  ||  Error
     else
-        echo  "Renamed \".commit\" folder to new \"${baseFolderPath}\" folder"
-        mv  ".commit"  "${baseFolderPath}"
+        echo  'Renamed ".commit" folder to new '"\"${baseFolderPath}\" folder"
+        mv  ".commit"  "${baseFolderPath}"  ||  Error
     fi
     if [ -e ".commit_ours" ]; then
-        echo  "Renamed \".commit_ours\" folder to \".commit_old_ours\" folder"
-        mv  ".commit_ours"  ".commit_old_ours"
+        echo  'Renamed ".commit_ours" folder to ".commit_old_ours" folder'
+        mv  ".commit_ours"  ".commit_old_ours"  ||  Error
     fi
-    echo  "Renamed \".commit_this\" folder to \".commit\" folder"
-    mv  ".commit_this"  ".commit"
+    echo  'Renamed ".commit_this" folder to ".commit" folder'
+    mv  ".commit_this"  ".commit"  ||  Error
+    EndInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
 }
 
 function  PullFile() {
@@ -894,8 +902,8 @@ function  PullFile() {
     local  rsyncUsed="${False}"
     if IsWindowsFolder  "${mergingFolderPath}"; then
         if [ "${LOCOMMIT_TMP}" != "" ]; then
-            RsyncToTemporary  "${mergingFolderPath}"  "${LOCOMMIT_TMP}"
             echo  "Using LOCOMMIT_TMP (${LOCOMMIT_TMP}) because \"${mergingFolderPath}\" is Windows shared folder."
+            RsyncToTemporary  "${mergingFolderPath}"  "${LOCOMMIT_TMP}"
             mergingFolderPath="${LOCOMMIT_TMP}${mergingFolderPath}"
             local  rsyncUsed="${True}"
         else
@@ -945,7 +953,8 @@ function  PullFile() {
 }
 
 function  InitBarePush() {
-    local  newRepositoryFolderPath=$( ResolvePath "$1"  || echo "(ERROR)" )
+    local  newRepositoryFolderPath="$1"
+    newRepositoryFolderPath=$( ResolvePath "${newRepositoryFolderPath}"  || echo "(ERROR)" )
     ErrorIfLastIs  "${newRepositoryFolderPath}"  "(ERROR)"
     if [ "${Options_Branch}" == "" ]; then
         local  branch="$( GetCurrentGitBranch )"
@@ -964,6 +973,7 @@ function  InitBarePush() {
         local  dotGitExistsInCurrentFolder="${False}"
     fi
     AssertNotExist  "${newRepositoryFolderPath}"
+    StartInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
     local  currentFolder="${PWD}"
     if [ "${dotGitExistsInCurrentFolder}" == "${False}" ]; then
         GitInit
@@ -984,18 +994,22 @@ function  InitBarePush() {
     mkdir -p ".commit_init-bare-push"
 
     git checkout-index -fau --prefix=".commit_init-bare-push/"
+    EndInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
 
     #// Create new repository
     mkdir -p "${newRepositoryFolderPath}"
     pushd  "${newRepositoryFolderPath}"  >  /dev/null
     local  newRepositoryFullPath="${PWD}"
+    StartInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
 
     git init --bare --shared=true
     git symbolic-ref HEAD refs/heads/${branch}
+    EndInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
     popd  >  /dev/null
 
     #// Make a commit
     pushd  ".commit_init-bare-push"  >  /dev/null
+    StartInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
 
     GitInit
     git remote add origin "file://${newRepositoryFullPath}"
@@ -1005,6 +1019,7 @@ function  InitBarePush() {
     git commit  -m "locommit) Created a local repository"  > /dev/null  2>&1
     git symbolic-ref HEAD refs/heads/${branch}
     git push --set-upstream origin ${branch}
+    EndInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
     popd  >  /dev/null
 
     #// Clean
@@ -1016,7 +1031,9 @@ function  InitBarePush() {
     AssertNotExist  ".commit_init-bare-push"
     echo  "Removed \".commit_init-bare-push\" temporary folder."
     if [ "${allFilesAreGitAdd}" == "${False}" ]; then
+        StartInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
         git reset  > /dev/null  2>&1
+        EndInTemporary  "LOCOMMIT_TMP"  "${LOCOMMIT_TMP}"
     fi
 }
 
@@ -1189,37 +1206,86 @@ function  DeleteFolder() {
     done
 }
 
+function  StartInTemporary() {
+    local  temporaryPathVariableName="$1"
+    local  temporaryPathValue="$2"
+    local  currentFolder="${PWD}"
+
+    if IsWindowsFolder  "${currentFolder}"; then
+        if [ "${temporaryPathValue}" != "" ]; then
+            echo  "Using ${temporaryPathVariableName} (${temporaryPathValue}) because \"${currentFolder}\" is Windows shared folder."
+
+            RsyncToTemporary  "${currentFolder}"  "${temporaryPathValue}"
+
+            pushd  "${temporaryPathValue}${currentFolder}" > /dev/null  ||  Error
+        else
+            echo  "${temporaryPathVariableName} environment variable is not set though \"${currentFolder}\" is Windows shared folder."
+        fi
+    fi
+}
+
+function  EndInTemporary() {
+    local  temporaryPathVariableName="$1"
+    local  temporaryPathValue="$2"
+    local  currentFolder="${PWD}"
+    if [ "${temporaryPathValue}" == "" ]; then
+        return
+    fi
+
+    if StartsWith  "${currentFolder}/"  "${temporaryPathValue}/"; then
+
+        RsyncFromTemporary  "${currentFolder}"  "${temporaryPathValue}"
+
+        popd  > /dev/null
+    fi
+}
+
 function  RsyncToTemporary() {
     local  folderPath="$1"
     local  temporaryPath="$2"
+    local  waitTime="$3"  #// "", 0 or 1s.  ""=1s
+    if [ "${waitTime}" == "" ]; then
+        waitTime="1s"
+    fi
     test  "${folderPath:0:1}" == "/"  ||  Error  "ERROR: RsyncToTemporary requests full path. folderPath: \"${folderPath}\""
     test  "${temporaryPath:0:1}" == "/"  ||  Error  "ERROR: RsyncToTemporary requests full path. temporaryPath: \"${temporaryPath}\""
     mkdir -p  "${temporaryPath}${folderPath}"
 
     rsync --recursive --delete --times  "${folderPath}/"  "${temporaryPath}${folderPath}/"  ||  Error
+        #// It is necessary to set "--times" for Windows share folder
+    sleep  "${waitTime}"
+    return 0
 }
 
 function  RsyncFromTemporary() {
+    #// Command "RsyncFromTemporary /tmp/folder/to /tmp" copies to /folder/to
     local  folderPathInTemporary="$1"
     local  temporaryPath="$2"
+    local  waitTime="$3"  #// "", 0 or 1s.  ""=1s
+    if [ "${waitTime}" == "" ]; then
+        waitTime="1s"
+    fi
     test  "${folderPathInTemporary:0:1}" == "/"  ||  Error  "ERROR: RsyncFromTemporary requests full path. folderPathInTemporary: \"${folderPathInTemporary}\""
     test  "${temporaryPath:0:1}" == "/"  ||  Error  "ERROR: RsyncFromTemporary requests full path. temporaryPath: \"${temporaryPath}\""
     StartsWith  "${folderPathInTemporary}/"  "${temporaryPath}/"  ||  Error
-    local  folderPath="${folderPathInTemporary:${#temporaryPath}}"
-    mkdir -p  "${folderPath}"
-    local  readOnlyFiles="$( find "${folderPath}" -type f ! -perm -u=w )"
+
+    local  destinationFolderPath="${folderPathInTemporary:${#temporaryPath}}"
+    mkdir -p  "${destinationFolderPath}"
+    local  readOnlyFiles="$( find "${destinationFolderPath}" -type f ! -perm -u=w )"
     echo  "${readOnlyFiles}"  |  xargs -I{} chmod 777 "{}"  #// For rsync can overwrite files in Windows share folder
 
-    rsync --recursive --delete --times --inplace  "${folderPathInTemporary}/"  "${folderPath}/"  ||  Error
+    rsync --recursive --delete --times --inplace  "${folderPathInTemporary}/"  "${destinationFolderPath}/"  ||  Error
         #// It is necessary to set "--inplace" for Windows share folder. "--inplace" does not rename in rsync.
     echo  "${readOnlyFiles}"  |  xargs -I{}  sh -c 'test -e "{}"  &&  chmod 444 "{}"'
         #// For not changed read only files in Windows share folder
+    sleep  "${waitTime}"
     return 0
 }
 
 function  IsWindowsFile() {  #// Shared file with Windows in Linux process
     local  filePath="$1"
     if [ -d "${filePath}" ]; then Error ;fi
+
     if df -h "${filePath}"  |  grep -E '/dev/' > /dev/null; then  #// Linux file system
         return "${False}"  #// Linux file
     else
@@ -1230,6 +1296,7 @@ function  IsWindowsFile() {  #// Shared file with Windows in Linux process
 function  IsWindowsFolder() {
     local  folderPath="$1"
     echo  "x"  >  "${folderPath}/.commit_tmp"
+
     IsWindowsFile  "${folderPath}/.commit_tmp"
     local  returnValue=$?
     rm  "${folderPath}/.commit_tmp"
@@ -1407,46 +1474,57 @@ function  AssertInstalled() {
     fi
 }
 
-#// pp "$config"
-#// pp "$config" config
-#// pp "$array" array  ${#array[@]}  "${array[@]}"
-#// $( pp "$config" >&2 )
+# pp
+#     Debug print
+# Example:
+#     pp "$config"
+#     pp "$config" config
+#     pp "$array" array  ${#array[@]}  "${array[@]}"
+#     pp "123"
+#     $( pp "$config" >&2 )
 function  pp() {
     local  value="$1"
     local  variableName="$2"
-    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi
+    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi  #// Add spaces
     local  oldIFS="$IFS"
     IFS=$'\n'
     local  valueLines=( ${value} )
     IFS="$oldIFS"
-    if [[ "$(declare -p ${variableName})" =~ "declare -a" ]]; then
-        local  type="array"
-    elif [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
-        local  type="oneLine"
-    else
-        local  type="multiLine"
+
+    local  type=""
+    if [ "${variableName}" != "" ]; then
+        if [[ "$(declare -p ${variableName} 2>&1 )" =~ "declare -a" ]]; then
+            local  type="array"
+        fi
+    fi
+    if [ "${type}" == "" ]; then
+        if [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
+            local  type="oneLine"
+        else
+            local  type="multiLine"
+        fi
     fi
 
     if [[ "${type}" == "oneLine" ]]; then
-        echo  "@@@${variableName}= \"${value}\" ---------------------------"
+        echo  "@@@${variableName}= \"${value}\" ---------------------------"  >&2
     elif [[ "${type}" == "multiLine" ]]; then
-        echo  "@@@${variableName}---------------------------"
-        echo  "\"${value}\""
+        echo  "@@@${variableName}---------------------------"  >&2
+        echo  "\"${value}\"" >&2
     elif [[ "${type}" == "array" ]]; then
-        echo  "@@@${variableName}---------------------------"
+        echo  "@@@${variableName}---------------------------"  >&2
         local  count="$3"
         if [ "${count}" == "" ]; then
-            echo  "[0]: \"$4\""
-            echo  "[1]: ERROR: pp parameter is too few"
+            echo  "[0]: \"$4\""  >&2
+            echo  "[1]: ERROR: pp parameter is too few"  >&2
         else
-            local  i="0"
+            local  i=""
             for (( i = 0; i < ${count}; i += 1 ));do
-                echo  "[$i]: \"$4\""
+                echo  "[$i]: \"$4\""  >&2
                 shift
             done
         fi
     else
-        echo  "@@@${variableName}? ---------------------------"
+        echo  "@@@${variableName}? ---------------------------"  >&2
     fi
 }
 
