Fixed failed tests.

diff --git a/bin/locommit b/bin/locommit
--- a/bin/locommit
+++ b/bin/locommit
@@ -626,9 +626,12 @@ function  ErrorIfLastIs() {
 function  Error() {
     local  errorMessage="$1"
     local  exitCode="$2"
+    if [ "${errorMessage}" == "" ]; then
+        errorMessage="ERROR"
+    fi
     if [ "${exitCode}" == "" ]; then  exitCode=2  ;fi
 
-    echo  "ERROR: ${errorMessage}" >&2
+    echo  "${errorMessage}" >&2
     exit  "${exitCode}"
 }
 
diff --git a/test/test-locommit b/test/test-locommit
--- a/test/test-locommit
+++ b/test/test-locommit
@@ -1300,25 +1300,32 @@ function  Test_Assert() {
     AssertNotExist  "_testing/build/not_found"
     AssertInstalled  "cat"
 
-    StartErrorTest
+    local  out="$(x="$( 
         AssertExist  "_testing/build/not_found"
-    EndErrorTest  'ERROR: Not found "_testing/build/not_found"'
-    StartErrorTest
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+    local  out="$(x="$( 
         AssertNotExist  "_testing/build/out"
-    EndErrorTest  'ERROR: Found "_testing/build/out"'
-    StartErrorTest
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+    local  out="$(x="$( 
         AssertInstalled  "cats"
-    EndErrorTest  'ERROR: Not installed "cats" command'
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
 
-    StartErrorTest
+    local  out="$(x="$( 
         AssertReadOnly  "_testing/build/out"
-    EndErrorTest  'ERROR: Not read only file "_testing/build/out"'
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+
     chmod -w  "_testing/build/out"
     AssertReadOnly  "_testing/build/out"
 
-    StartErrorTest
+    local  out="$(x="$( 
         AssertNotReadOnly  "_testing/build/out"
-    EndErrorTest  'ERROR: Read only file "_testing/build/out"'
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+
     chmod +w  "_testing/build/out"
     AssertNotReadOnly  "_testing/build/out"
 
@@ -1326,22 +1333,28 @@ function  Test_Assert() {
     AssertExist  "_testing/build/out X"
     AssertNotExist  "_testing/build/out not_found"
 
-    StartErrorTest
+    local  out="$(x="$( 
         AssertExist  "_testing/build/out not_found"
-    EndErrorTest  'ERROR: Not found "_testing/build/out not_found"'
-    StartErrorTest
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+    local  out="$(x="$( 
         AssertNotExist  "_testing/build/out X"
-    EndErrorTest  'ERROR: Found "_testing/build/out X"'
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
 
-    StartErrorTest
+    local  out="$(x="$( 
         AssertReadOnly  "_testing/build/out X"
-    EndErrorTest  'ERROR: Not read only file "_testing/build/out X"'
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+
     chmod -w  "_testing/build/out X"
     AssertReadOnly  "_testing/build/out X"
 
-    StartErrorTest
+    local  out="$(x="$( 
         AssertNotReadOnly  "_testing/build/out X"
-    EndErrorTest  'ERROR: Read only file "_testing/build/out X"'
+    )" && echo "$x" || echo "(assert failed)" )"
+    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
+
     chmod +w  "_testing/build/out X"
     AssertNotReadOnly  "_testing/build/out X"
 }
@@ -1352,12 +1365,12 @@ function  AssertExist() {
     if [ "${leftOfWildcard}" == "${path}" ]; then  #// No wildcard
 
         if [ ! -e "${path}" ]; then
-            Error  "Not found \"${path}\""
+            Error  "ERROR: Not found \"${path}\""
         fi
     else
         local  rightOfWildcard="${path##*\*}"
         if [ ! -e "${leftOfWildcard}"*"${rightOfWildcard}" ]; then
-            Error  "Not found \"${path}\""
+            Error  "ERROR: Not found \"${path}\""
         fi
     fi
 }
@@ -1366,7 +1379,7 @@ function  AssertNotExist() {
     local  path="$1"
 
     if [ -e "${path}" ]; then
-        TestError  "ERROR: Found \"${path}\""
+        Error  "ERROR: Found \"${path}\""
     fi
 }
 
@@ -1378,7 +1391,7 @@ function  AssertReadOnly() {
     echo "${attributes:0:10}" | grep w  > /dev/null  &&  writable=${True}
 
     if [ "${writable}" == "${True}" ]; then
-        TestError  "ERROR: Not read only file \"${path}\""
+        Error  "ERROR: Not read only file \"${path}\""
     fi
 }
 
@@ -1390,7 +1403,7 @@ function  AssertNotReadOnly() {
     echo "${attributes:0:10}" | grep w  > /dev/null  &&  writable=${True}
 
     if [ "${writable}" == "${False}" ]; then
-        TestError  "ERROR: Read only file \"${path}\""
+        Error  "ERROR: Read only file \"${path}\""
     fi
 }
 
@@ -1400,7 +1413,7 @@ function  AssertInstalled() {
     which "${checkingCommand}" > /dev/null  &&  exists=${True}
 
     if [ "${exists}" == ${False} ]; then
-        TestError  "ERROR: Not installed \"${checkingCommand}\" command"
+        Error  "ERROR: Not installed \"${checkingCommand}\" command"
     fi
 }
 
@@ -1410,7 +1423,7 @@ function  AssertContents() {
 
     local  result="$(cat "${filePath}")"
     if [ "${result}" != "$( echo -e "${expectedContents}" )" ]; then
-        TestError  "Not expected contents in ${filePath}: ${result}"
+        Error  "ERROR: Not expected contents in ${filePath}: ${result}"
     fi
 }
 
@@ -1419,13 +1432,13 @@ function  Test_ErrorIfLastIs() {
     local  output="$( Test_Sub1_ErrorIfLastIs )"
     local  answer="$( echo -e 'OK\nstdout\n(ERROR)\n' )"
     if [ "${output}" != "${answer}" ]; then
-        TestError  "ERROR in Test_ErrorIfLastIs 1"
+        Error  "ERROR: in Test_ErrorIfLastIs 1"
     fi
 
     local  output="$( Test_Sub2_ErrorIfLastIs )"
     local  answer="$( echo -e '(error_symbol) OK\nPass\n' )"
     if [ "${output}" != "${answer}" ]; then
-        TestError  "ERROR in Test_ErrorIfLastIs 2"
+        Error  "ERROR: in Test_ErrorIfLastIs 2"
     fi
 }
 
@@ -1537,6 +1550,21 @@ function  EndErrorTest() {
     fi
 }
 
+# ExitIfMatched
+#     Check exit code and return code in $( ). If checking was failed, do "exit" command.
+# Example:
+#     local  out="$(x="$( command )" && echo "$x" || echo "(ERROR:$?)" )"
+#     ExitIfMatched  "${out}"  '^\(ERROR:([0-9]*)\)$'
+function  ExitIfMatched() {
+    local  output="$1"
+    local  regularExpression="$2"
+
+    if [[ "${output}" =~ ${regularExpression} ]]; then
+        local  exitCode="$( echo "${output}"  |  sed -E  's/'"${regularExpression}"'/\1/')"
+        exit  "${exitCode}"
+    fi
+}
+
 function  TestError() {
     local  errorMessage="$1"
     if [ "${errorMessage}" == "" ]; then
@@ -1551,6 +1579,18 @@ function  TestError() {
 }
 ErrorCount=0
 LastErrorMessage=""
+
+function  Error() {
+    local  errorMessage="$1"
+    local  exitCode="$2"
+    if [ "${errorMessage}" == "" ]; then
+        errorMessage="ERROR"
+    fi
+    if [ "${exitCode}" == "" ]; then  exitCode=2  ;fi
+
+    echo  "${errorMessage}" >&2
+    exit  "${exitCode}"
+}
 
 function  EndOfTest() {
     echo  ""
@@ -1567,21 +1607,52 @@ function  EndOfTest() {
 
 #// pp "$config"
 #// pp "$config" config
+#// pp "$array" array  ${#array[@]}  "${array[@]}"
+#// pp "123"
 #// $( pp "$config" >&2 )
 function  pp() {
     local  value="$1"
     local  variableName="$2"
-    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi
+    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi  #// Add spaces
     local  oldIFS="$IFS"
     IFS=$'\n'
     local  valueLines=( ${value} )
     IFS="$oldIFS"
 
-    if [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
-        echo  "@@@${variableName}= \"${value}\" ---------------------------"
+    local  type=""
+    if [ "${variableName}" != "" ]; then
+        if [[ "$(declare -p ${variableName} 2>&1 )" =~ "declare -a" ]]; then
+            local  type="array"
+        fi
+    fi
+    if [ "${type}" == "" ]; then
+        if [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
+            local  type="oneLine"
+        else
+            local  type="multiLine"
+        fi
+    fi
+
+    if [[ "${type}" == "oneLine" ]]; then
+        echo  "@@@${variableName}= \"${value}\" ---------------------------"  >&2
+    elif [[ "${type}" == "multiLine" ]]; then
+        echo  "@@@${variableName}---------------------------"  >&2
+        echo  "\"${value}\"" >&2
+    elif [[ "${type}" == "array" ]]; then
+        echo  "@@@${variableName}---------------------------"  >&2
+        local  count="$3"
+        if [ "${count}" == "" ]; then
+            echo  "[0]: \"$4\""  >&2
+            echo  "[1]: ERROR: pp parameter is too few"  >&2
+        else
+            local  i="0"
+            for (( i = 0; i < ${count}; i += 1 ));do
+                echo  "[$i]: \"$4\""  >&2
+                shift
+            done
+        fi
     else
-        echo  "@@@${variableName}---------------------------"
-        echo  "\"${value}\""
+        echo  "@@@${variableName}? ---------------------------"  >&2
     fi
 }
 
